### ISSUE TITLE
Fails parsing VyOS 1.1.7 config

### ISSUE THREAD

**Issue by jantman** [hedin/vyatta-conf-parser#5]
I attempted to parse a config from my VyOS 1.1.7 router, and it's failing with this error:

```
Traceback (most recent call last):
  File "newconf.py", line 8, in <module>
    p = vparser.parse_conf(conf)
  File "/home/jantman/GIT/apt-er01-vyos/acceptance/lib/python2.7/site-packages/vyattaconfparser/parser.py", line 102, in parse_conf
    c, headers = parse_node(c, line, headers)
  File "/home/jantman/GIT/apt-er01-vyos/acceptance/lib/python2.7/site-packages/vyattaconfparser/parser.py", line 63, in parse_node
    update_tree(config, headers, {h: {}})
  File "/home/jantman/GIT/apt-er01-vyos/acceptance/lib/python2.7/site-packages/vyattaconfparser/parser.py", line 33, in update_tree
    t[list(i.keys())[0]] = {}
TypeError: list indices must be integers, not unicode
```

I'll be working on test code and a fix as a PR, I hope...

PS - using 0.4.4 from PyPI on Python 2.7.

**Comment by jantman** [comment]
It appears that the problem is in VyOS 1.1.7 (or something between VC6.3 and VyOS 1.1.7), empty braces are no longer present in the config, which really complicates parsing it this way...

VC 6.3:

```
system {
    ntp {
        server 0.vyatta.pool.ntp.org {
        }
        server 1.vyatta.pool.ntp.org {
        }
        server 2.vyatta.pool.ntp.org {
        }
        server us.pool.ntp.org {
            prefer
        }
    }
}
```

VyOS 1.1.7:

```
system {
    ntp {
        server 0.vyatta.pool.ntp.org
        server 1.vyatta.pool.ntp.org
        server 2.vyatta.pool.ntp.org
        server us.pool.ntp.org {
            prefer {
            }
        }
    }
}
```

So the config now only contains the trailing braces if there's something in that section. This trips up the parsing code, because the first line (`server 0.vyatta.pool.ntp.org`) sets `[system][ntp][server]` to be a list, but the last line (`server us.pool.ntp.org {`) attempts to append to it like a dict.

**Comment by miron0xff** [comment]
Hi, Jason!
I don't know how should parsed config looks like in this situation.
Should it be a composite list of `strings` (if there is no braces) and `dicts` (if it ends with brace), or it should be a `dict` of `dicts` if there is at least one item with something in it.

``` python
# Like this
'system': {
    'ntp': {
        'server': [
            '0.vyatta.pool.ntp.',
            '1.vyatta.pool.ntp.org',
            '2.vyatta.pool.ntp.org',
            {'us.pool.ntp.org': {'prefer': {}}},
        ]
    }
}
# or like this
'system': {
    'ntp': {
        'server': {
            '0.vyatta.pool.ntp.org': {},
            '1.vyatta.pool.ntp.org': {},
            '2.vyatta.pool.ntp.org': {},
            'us.pool.ntp.org': {'prefer': {}},
        }
    }
}
```

The main question is: should we convert all parent section or only one item in it?

**Comment by jantman** [comment]
Honestly I'm not entirely sure... my gut reaction would be #2, that it should just be a dict of dicts, and code that uses this should just know that an empty dict is omitted in the newer config versions.

But it really doesn't matter all that much to me... the code I'm using this in is brand new, so I can deal with it either way.

Side note: why does everyone need to invent their own config format? It would be so much nicer if this was just JSON, or YAML, or... for that matter... anything that has an existing parser.

For what it's worth, it's illegible Perl, but the upstream VyOS config parsing appears to live at https://github.com/vyos/vyatta-cfg

**Comment by miron0xff** [comment]
> why does everyone need to invent their own config format?

The first question I asked myself when started to work with Vyatta two years ago =)

**Comment by miron0xff** [comment]
Sorry for late reply I was a little busy those days.

I added new branch called [v117conf](https://github.com/hedin/vyatta-conf-parser/tree/v117conf) with experimental support for new config style.

Your config example parses well with new code (there is test for it), but one other test fails =).

Also there is no PY3 support at this time. I'll fix all later.
